# Generated by Django 6.1 on 2026-08-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticPatient',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Consent Verified', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=255)),
                ('risk', models.IntegerField(default=0)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('ehr_notes', models.TextField(blank=True, default='')),
                ('doctor_npi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.syntheticnpi')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
        ),
    ]
