# Generated by Django 6.1 on 2026-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_actor_auditlog_device_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='npi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
