# Generated by Django 6.1 on 2026-08-17 06:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_nextconsultation_patientallergy_patientcondition_and_more'),
        ('patients', '0003_familypatientlink_can_edit_clinical_patient_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('DEVICE', 'Device / ESP32')], default='MANUAL', max_length=20)),
                ('entered_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_glucose', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_vitals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
        ),
    ]
