# Generated by Django 6.1 on 2026-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
