# Generated by Django 6.1 on 2026-08-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconnectionrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='doctorconnectionrequest',
            name='doctor_npi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='doctors.syntheticnpi'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientlink',
            unique_together={('patient', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorconnectionrequest',
            unique_together={('patient', 'doctor_npi')},
        ),
    ]
