# Generated by Django 6.1 on 2026-08-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('registration_identifier', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDoctorRegistry',
            fields=[
                ('registration_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('council', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('registration_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_registration_number', models.CharField(max_length=50)),
                ('state_medical_council', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=100)),
                ('additional_qualifications', models.CharField(blank=True, max_length=255, null=True)),
                ('hpr_id', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='PENDING', max_length=25)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorFacilityAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employment_status', models.CharField(default='Active', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_source', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_affiliations', to='doctors.doctorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_affiliations', to='doctors.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('PROFESSIONAL_REGISTRATION', 'Professional Registration'), ('IDENTITY_MATCH', 'Identity Match'), ('QUALIFICATION', 'Qualification'), ('HOSPITAL_AFFILIATION', 'Hospital Affiliation'), ('ADMIN_REVIEW', 'Admin Review')], max_length=30)),
                ('source', models.CharField(max_length=150)),
                ('result', models.CharField(choices=[('EXACT_MATCH', 'Exact Match'), ('LIKELY_MATCH', 'Likely Match'), ('MISMATCH', 'Mismatch'), ('NOT_FOUND', 'Not Found'), ('MANUAL_REVIEW', 'Manual Review')], max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
