# Generated by Django 6.1 on 2026-08-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_healthfacility_referencedoctorregistry_doctorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinary_id', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(db_index=True, max_length=50)),
                ('doctor_name', models.CharField(max_length=100)),
                ('state_medical_council', models.CharField(max_length=150)),
                ('action_type', models.CharField(max_length=50)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('suspended_date', models.DateField(blank=True, null=True)),
                ('restored_date', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(default='SYNTHETIC_TEST_REFERENCE', max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDoctorAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(default='PENDING', max_length=20)),
                ('source_type', models.CharField(default='SYNTHETIC_REFERENCE', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='facility_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='source_type',
            field=models.CharField(blank=True, default='SYNTHETIC_REFERENCE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='registration_status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='source_reference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='source_type',
            field=models.CharField(default='SYNTHETIC_REFERENCE', max_length=50),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='source_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedoctorregistry',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='referencedoctorregistry',
            name='council',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='referencedoctorregistry',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='referencedoctorregistry',
            index=models.Index(fields=['normalized_name'], name='doctors_ref_normali_b9b32c_idx'),
        ),
        migrations.AddIndex(
            model_name='referencedoctorregistry',
            index=models.Index(fields=['council'], name='doctors_ref_council_7bf5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='referencedoctorregistry',
            index=models.Index(fields=['registration_status'], name='doctors_ref_registr_fcb74d_idx'),
        ),
        migrations.AddField(
            model_name='doctordisciplinaryrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='doctors.referencedoctorregistry'),
        ),
        migrations.AddField(
            model_name='referencedoctoraffiliation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_doctor_affiliations', to='doctors.healthfacility'),
        ),
        migrations.AddField(
            model_name='referencedoctoraffiliation',
            name='reference_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='doctors.referencedoctorregistry'),
        ),
    ]
