# Generated by Django 6.1 on 2026-08-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctordisciplinaryrecord_referencedoctoraffiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticnpi',
            name='npi',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
