from datetime import date
from ai_services.models import MedicationKnowledgeBase

SEED_MEDICATIONS = [
    {
        'generic_name': 'Levetiracetam',
        'brand_names': 'Keppra',
        'medication_class': 'Anticonvulsant / Anti-epileptic',
        'general_uses': 'Indicated for adjunctive treatment of partial onset seizures, myoclonic seizures, and primary generalized tonic-clonic seizures in patients with epilepsy.',
        'common_precautions': 'May cause somnolence, fatigue, and behavioral changes. Do not abruptly discontinue.',
        'common_contraindications': 'Hypersensitivity to Levetiracetam or pyrrolidone derivatives.',
        'allergy_considerations': 'Check for known hypersensitivity to Levetiracetam.',
        'common_interactions': 'Minor interactions with other sedating agents.',
        'dosage_reference': 'Reference adult starting dose: 500 mg twice daily. Dose adjustments required for renal impairment.',
        'age_precautions': 'Pediatric and elderly patients require body weight or renal clearance dosing adjustment.',
        'pregnancy_precautions': 'Use during pregnancy only if potential benefit justifies potential risk to fetus.',
        'category': 'PRESCRIPTION_MEDICINE',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    },
    {
        'generic_name': 'Penicillin V',
        'brand_names': 'Pen-VK, Veetids',
        'medication_class': 'Penicillin Antibiotic',
        'general_uses': 'Treatment of mild to moderately severe bacterial infections caused by penicillin-sensitive microorganisms.',
        'common_precautions': 'Serious and occasionally fatal hypersensitivity (anaphylactic) reactions have been reported.',
        'common_contraindications': 'Known hypersensitivity to Penicillin, Amoxicillin, Ampicillin, or beta-lactam antibiotics.',
        'allergy_considerations': 'STRICT CONTRAINDICATION in patients with recorded Penicillin allergy or cephalosporin cross-reactivity.',
        'common_interactions': 'Decreases effectiveness of oral contraceptives. Reduced clearance with Probenecid.',
        'dosage_reference': 'Reference adult dose: 250 mg to 500 mg every 6 to 8 hours for 10 days.',
        'age_precautions': 'Dosage calculation based on body weight in pediatric patients.',
        'pregnancy_precautions': 'FDA Pregnancy Category B. Generally considered safe when clinically indicated.',
        'category': 'PRESCRIPTION_MEDICINE',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    },
    {
        'generic_name': 'Paracetamol',
        'brand_names': 'Tylenol, Panadol, Acetaminophen',
        'medication_class': 'Analgesic / Antipyretic',
        'general_uses': 'Temporary relief of mild to moderate pain, headaches, muscle aches, and fever reduction.',
        'common_precautions': 'Do not exceed 4000 mg (4 grams) per 24 hours. Avoid concurrent alcohol consumption.',
        'common_contraindications': 'Severe hepatic impairment or severe active liver disease.',
        'allergy_considerations': 'Rare cases of severe skin reactions (Stevens-Johnson syndrome). Discontinue if skin rash occurs.',
        'common_interactions': 'Chronic high-dose use may enhance anticoagulant effect of Warfarin.',
        'dosage_reference': 'Reference adult dose: 325 mg to 650 mg every 4 to 6 hours as needed (Max 4000 mg/day).',
        'age_precautions': 'Pediatric formulations require age and weight-based dosing tables.',
        'pregnancy_precautions': 'Generally considered safe for short-term use during pregnancy at recommended doses.',
        'category': 'OTC_INFORMATION',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    },
    {
        'generic_name': 'Ibuprofen',
        'brand_names': 'Advil, Motrin, Nurofen',
        'medication_class': 'NSAID (Nonsteroidal Anti-inflammatory Drug)',
        'general_uses': 'Relief of mild to moderate pain, inflammatory conditions, dysmenorrhea, and fever.',
        'common_precautions': 'May increase risk of serious gastrointestinal ulceration, bleeding, and cardiovascular thrombotic events.',
        'common_contraindications': 'Active peptic ulcer, severe heart failure, severe renal failure, third trimester of pregnancy.',
        'allergy_considerations': 'Do not use in patients who have experienced asthma, urticaria, or allergic reactions after taking Aspirin or NSAIDs.',
        'common_interactions': 'Interacts with Warfarin (bleeding risk), ACE inhibitors (reduced antihypertensive effect), Lithium.',
        'dosage_reference': 'Reference adult dose: 200 mg to 400 mg every 4 to 6 hours (Max 1200 mg OTC / 3200 mg Rx).',
        'age_precautions': 'Not recommended for infants under 6 months without physician instruction.',
        'pregnancy_precautions': 'Avoid use at 30 weeks gestation and later due to premature closure of ductus arteriosus.',
        'category': 'OTC_INFORMATION',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    },
    {
        'generic_name': 'Warfarin',
        'brand_names': 'Coumadin, Jantoven',
        'medication_class': 'Anticoagulant',
        'general_uses': 'Prophylaxis and treatment of venous thrombosis, pulmonary embolism, and thromboembolic complications associated with atrial fibrillation.',
        'common_precautions': 'Requires regular INR blood monitoring. High risk of major or fatal bleeding.',
        'common_contraindications': 'Pregnancy, hemorrhagic tendencies, recent eye/brain surgery, uncontrolled hypertension.',
        'allergy_considerations': 'Known hypersensitivity to Warfarin.',
        'common_interactions': 'Extremely high interaction potential with antibiotics, NSAIDs, Aspirin, Vitamin K, and alcohol.',
        'dosage_reference': 'Individualized based on target INR ratio as prescribed by attending hematologist/physician.',
        'age_precautions': 'Elderly patients demonstrate greater sensitivity to Warfarin.',
        'pregnancy_precautions': 'STRICTLY CONTRAINDICATED in pregnancy (Teratogenic - causes fetal bleeding/malformation).',
        'category': 'RESTRICTED',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    },
    {
        'generic_name': 'Aspirin',
        'brand_names': 'Bayer, Ecotrin',
        'medication_class': 'NSAID / Antiplatelet',
        'general_uses': 'Analgesic, anti-inflammatory, antipyretic, and secondary prevention of cardiovascular events.',
        'common_precautions': 'Risk of gastrointestinal bleeding and tinnitus.',
        'common_contraindications': 'Children/teenagers with viral infections (Reye syndrome risk), active GI bleeding.',
        'allergy_considerations': 'Contraindicated in patients with Aspirin triad or recorded NSAID allergy.',
        'common_interactions': 'Enhances bleeding risk with Warfarin, Heparin, and SSRIs.',
        'dosage_reference': 'Cardioprotective dose: 81 mg daily. Pain/fever dose: 325 mg to 650 mg every 4 hours.',
        'age_precautions': 'Do not give to children/teenagers with chickenpox or flu symptoms due to Reye syndrome.',
        'pregnancy_precautions': 'Avoid high doses in third trimester.',
        'category': 'OTC_INFORMATION',
        'source_reference': 'FDA Approved Drug Label / National Formulary 2026',
    }
]

def seed_medication_knowledge_base():
    for item in SEED_MEDICATIONS:
        MedicationKnowledgeBase.objects.get_or_create(
            generic_name=item['generic_name'],
            defaults=item
        )
