# Generated by Django 6.1 on 2026-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticDevice',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(default='Unassigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
