# Generated by Django 6.1 on 2026-08-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('accel_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accel_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accel_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gyro_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gyro_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gyro_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fall_detected', models.BooleanField(default=False)),
                ('esp32_connected', models.BooleanField(default=True)),
                ('esp32_battery', models.IntegerField(blank=True, null=True)),
                ('esp32_rssi', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='patients.patient')),
            ],
        ),
    ]
