# Generated by Django 6.1 on 2026-08-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_familypatientlink_can_edit_clinical_patient_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('brand_names', models.CharField(blank=True, default='', max_length=255)),
                ('medication_class', models.CharField(db_index=True, max_length=150)),
                ('general_uses', models.TextField(blank=True, default='')),
                ('common_precautions', models.TextField(blank=True, default='')),
                ('common_contraindications', models.TextField(blank=True, default='')),
                ('allergy_considerations', models.TextField(blank=True, default='')),
                ('common_interactions', models.TextField(blank=True, default='')),
                ('dosage_reference', models.TextField(blank=True, default='')),
                ('age_precautions', models.TextField(blank=True, default='')),
                ('pregnancy_precautions', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('GENERAL_INFORMATION', 'General Information'), ('OTC_INFORMATION', 'Over-The-Counter Information'), ('PRESCRIPTION_MEDICINE', 'Prescription Required Medicine'), ('RESTRICTED', 'Restricted Medicine')], default='PRESCRIPTION_MEDICINE', max_length=30)),
                ('source_reference', models.CharField(default='FDA Label Registry / National Formulary 2026', max_length=255)),
                ('source_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMedicationReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=150)),
                ('question', models.TextField()),
                ('safety_status', models.CharField(default='REVIEW_RECOMMENDED', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Doctor Review'), ('REVIEWED', 'Reviewed by Clinician'), ('DECLINED', 'Declined')], default='PENDING', max_length=30)),
                ('doctor_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_medication_reviews', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_review_requests', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_medication_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
