# Generated by Django 6.1 on 2026-08-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverpatientlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='caregiverpatientlink',
            unique_together={('caregiver', 'patient')},
        ),
    ]
