# Generated by Django 6.1 on 2026-08-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_type', models.CharField(choices=[('PROFESSIONAL', 'Professional Caregiver'), ('FAMILY', 'Family/Personal Caregiver')], default='PROFESSIONAL', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True, null=True)),
                ('previous_experience', models.TextField(blank=True, null=True)),
                ('current_agency', models.CharField(blank=True, max_length=150, null=True)),
                ('agency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
